### ISSUE TITLE
Unable to refresh or log water on Versa.

### ISSUE THREAD

**Issue by alyssacodes** [tylerl0706/Water-Logged#5]
The app worked for a few days before bricking. The message is to restart the app (done that, as well as reinstalling it), which seems to mean it's either not connecting or timing out. Could this have something to do with Fitbit depreciating it's OAuth1 this month in favor of OAuth2?

**Comment by TylerLeonhardt** [comment]
Thanks for this! 

I just tested it and my Ionic is working so I don't think it's the deprecation also because I'm pretty sure I'm using OAuth2.

That said, what I've noticed is that there's occasionally a communication issue between the app on the watch and the companion process running on the phone when your phone hasn't synced for some time.

**Comment by TylerLeonhardt** [comment]
I personally have had a bunch of sync issues with the Versa with my phone (OnePlus 3) because it's not a supported device.

These sync issues sadly bubble up to failed attempts grab the latest water data from fitbit

**Comment by TylerLeonhardt** [comment]
Could this explain your situation?

**Comment by alyssacodes** [comment]
I am using a Samsung Galaxy S7 Edge so I don't think it has anything to do with my particular phone. This is also being reported by several other people with various phones in the Fitbit Versa Group page on Facebook and on the Fitbit Community pages. Also I forgot to mention when the app glitches out in this way it breaks the Digilog clock face (Haven't check other clock faces). This only happens when the Water Logged app says to restart the app. The only way to fix the clock face at that point is to open a working app or 'Today' and then it fixes itself.

**Comment by TylerLeonhardt** [comment]
> This is also being reported by several other people with various phones in the Fitbit Versa Group page on Facebook and on the Fitbit Community pages

About WaterLogged or about sync issues? Can you link me to the fb group, I'd like to join 😄

**Comment by TylerLeonhardt** [comment]
> Also I forgot to mention when the app glitches out in this way it breaks the Digilog clock face (Haven't check other clock faces). This only happens when the Water Logged app says to restart the app. The only way to fix the clock face at that point is to open a working app or 'Today' and then it fixes itself.

This leads me to believe that Fitbit itself is having a problem. Water Logged is really a quite trivial app. All it does is grab the latest data from fitibit via the Companion API and send the data to the watch. Not doing anything too crazy there.

Still, I will investigate further. I might have to ask some fitbit dev rel what I'm doing wrong.

**Comment by alyssacodes** [comment]
https://www.facebook.com/groups/fitbitversa/?ref=br_rs

I'm thinking you might be right about it being a Fitbit issue because the other water app is also not working at this time.

**Comment by TylerLeonhardt** [comment]
It's very likely. Try to get your watch to sync properly (like sync steps I mean) then go straight to WaterLogged and see if it refreshes.

**Comment by alyssacodes** [comment]
The other day my watch was finally dying so I thought I'd trying shutting it down to charge (hoping it would charge faster). Ever since I've turned it back on the app has been working as expected. I suppose the users should be rebooting their devices (at least after the initial update when you first receive the device) since this seems to be solving various problems users have been having. I usually reboot my pc after any serious install so I'm not sure why I don't think to do that on other devices.

**Comment by TylerLeonhardt** [comment]
Glad it's back to normal! Seems to be a fitbit issue then. Thanks for the follow up!
